studentcourse:
  mysql:
    host: ${MYSQL_HOST:mysql}
    port: ${MYSQL_PORT:3306}
  eureka:
    default-zone: http://eureka-service:8761/eureka/
  frontend:
    origin: http://localhost
    https-origin: https://localhost
  nginx:
    origin: http://localhost
    https-origin: https://localhost

eureka:
  instance:
    prefer-ip-address: true
