studentcourse:
  mysql:
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
  eureka:
    default-zone: http://localhost:8761/eureka/
  frontend:
    origin: http://localhost:5173
    https-origin: https://localhost:5173
  nginx:
    origin: http://localhost
    https-origin: https://localhost
