apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: student-course
spec:
  type: NodePort
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      nodePort: 30310
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: student-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
        app.kubernetes.io/part-of: student-course-cloud
    spec:
      nodeSelector:
        scms-role: data
      containers:
        - name: loki
          image: grafana/loki:3.1.1
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/loki-config.yml
          ports:
            - containerPort: 3100
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 384Mi
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki-config.yml
              subPath: loki-config.yml
              readOnly: true
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: student-course
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
        app.kubernetes.io/part-of: student-course-cloud
    spec:
      nodeSelector:
        scms-log: enabled
      containers:
        - name: promtail
          image: grafana/promtail:3.1.1
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/promtail/promtail-config.yml
          ports:
            - containerPort: 9080
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 192Mi
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail/promtail-config.yml
              subPath: promtail-config.yml
              readOnly: true
            - name: positions
              mountPath: /run/promtail
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: positions
          emptyDir: {}
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
