apiVersion: v1
kind: Secret
metadata:
  name: scms-secrets
  namespace: student-course
  labels:
    app.kubernetes.io/part-of: student-course-cloud
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "123888"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "123888"
  JWT_SECRET: "local-demo-secret-change-me"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "admin"
