input {
  file {
    path => [
      "/logs/eureka-service/*.log",
      "/logs/gateway-service/*.log",
      "/logs/student-service/*.log",
      "/logs/course-service/*.log",
      "/logs/teacher-service/*.log",
      "/logs/enrollment-service/*.log",
      "/logs/nginx/*.log",
      "/logs/mysql/*.log"
    ]
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb"
  }
}

filter {
  mutate {
    add_field => { "project" => "student-course-cloud" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "student-course-cloud-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
