input {
  file {
    path => [
      "/var/log/containers/*student-course*.log",
      "/var/log/containers/*scms*.log",
      "/var/log/containers/*config-service*.log",
      "/var/log/containers/*eureka-service*.log",
      "/var/log/containers/*gateway-service*.log",
      "/var/log/containers/*student-service*.log",
      "/var/log/containers/*course-service*.log",
      "/var/log/containers/*teacher-service*.log",
      "/var/log/containers/*enrollment-service*.log",
      "/var/log/containers/*nginx*.log"
    ]
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb"
  }
}

filter {
  mutate {
    add_field => { "project" => "student-course-cloud" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "student-course-cloud-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
