server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: student-course-pods
    static_configs:
      - targets:
          - localhost
        labels:
          job: student-course-pods
          namespace: student-course
          __path__: /var/log/containers/*_student-course_*.log
